### ISSUE TITLE
DX11 Refract shader mostly appears black

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1477]
**Describe the bug**
It seems like materials using "Refract" don't render correctly in Dx11. I'm guessing this is less of a bug and more of an implemented feature but I noticed it and figured tracking beats forgetting until later. The texture appears mostly fine but has some extra dark coloring going on around the borders of the brush. 

**To Reproduce**
1. Load any map that uses a problematic texture such as [https://tempus.xyz/maps/jump_rat_rc4](https://tempus.xyz/maps/jump_rat_rc4)
2. Notice the textures sometimes appear slightly darker around the border than they would in TF2

**Expected behavior**
![image](https://user-images.githubusercontent.com/62961532/137233953-40c38b05-9b50-4474-ba23-02a0030af099.png)

Should become:

![image](https://user-images.githubusercontent.com/62961532/137233833-7672de65-8b6d-435d-aa0a-13c3772b9908.png)

**Desktop (*please complete the following information*):**
 - OS: Windows
 - Renderer: DX11
 - UI: Panorama

**Comment by hexaflexahexagon** [comment]
Most of the textures look better but still aren't quite the same as tf2. for example this:
![image](https://user-images.githubusercontent.com/62961532/137233833-7672de65-8b6d-435d-aa0a-13c3772b9908.png)
![image](https://user-images.githubusercontent.com/62961532/137234006-20532096-ad57-499c-a919-e31fde6d40ff.png)

Looks like this:
![image](https://user-images.githubusercontent.com/62961532/137233953-40c38b05-9b50-4474-ba23-02a0030af099.png)
![image](https://user-images.githubusercontent.com/62961532/137233990-936440b9-82e4-49e5-97dc-c5efd46344b0.png)

I'll edit the original issue to more closely match what it looks like now.

**Comment by Gocnak** [comment]
Looks like this may have been fixed in the recent DX11 fixes, awaiting push to Steam and reverifying.

**Comment by hexaflexahexagon** [comment]
looks good now

**Comment by granis48** [comment]
This does not seem to be fixed. 

[surf_benevolent](https://teamstorage.momentum-mod.org/s/3dXaiS64itceEY8) has these waterfall/river Refract materials behind all stage teleports that appear almost pitch black in the current version of momentum mod. 
Here's what they look like in css: 
![image](https://github.com/momentum-mod/game/assets/52294733/4f073053-1e70-4873-bb2e-90e46d1a8f66)

Here's what they look like in mom playtest: 
![image](https://github.com/momentum-mod/game/assets/52294733/30002079-d93e-49c8-9c93-7b42e9c3d998)

And here is what they look like if i simply decompile the map and compile it with momentum hammer: 
![image](https://github.com/momentum-mod/game/assets/52294733/d4440ec6-df56-4d1d-81a7-987fcfaeb243)

(Just noticed i had mat_brightness set to 1.25 in momentum mod screenshots but that doesn't affect the problem)

**Comment by Gocnak** [comment]
This is fixed in the 0.10.0 release. Shoutouts to SRGB

**Comment by granis48** [comment]
This is still not fixed....
surf_shodan css version: 
<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/6f6d12c1-524b-4e23-9f0a-e42aeaba14d8" />

the same css version of surf_benevolent as before: 
<img width="1843" height="1260" alt="Image" src="https://github.com/user-attachments/assets/b3148b6e-b399-41f5-97d8-a31319e067a4" />

Worth noting is they're all applied to func_brush entities

**Comment by JJL772** [comment]
Your latest screenshots look like a different issue, not related to SRGB reads. Those surfaces look completely black to me. 
I suggest opening a separate issue for that.

**Comment by granis48** [comment]
Alright will do
edit: https://github.com/momentum-mod/game/issues/2556

**Comment by JJL772** [comment]
Thanks!

**Comment by Gocnak** [comment]
Oops missed the comments up there, ty for the new issue
