### ISSUE TITLE
movement limit trigger can be bypassed for 1 tick when leaving practice mode

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1676]
### Describe the bug

see video by Mr Bururguersers who reported this:
https://cdn.discordapp.com/attachments/235125108656701440/939291757236092958/2022-02-04_22-45-03.mp4

note, this may be fixed when practice mode gets converted to use the saveloc system internally. we should check back on this after that.

### How To Reproduce

1. stand in limit movement trigger, most noticeably one that blocks jump
2. enter practice mode
3. hold jump
4. exit practice mode
5. forbidden jump

### Expected Behavior

no jump

### Operating System

Windows 10

### Renderer

DX11 (default)

**Comment by Syrreal** [comment]
For slide triggers this bug still happens using savelocs. If you make a save inside of the slide trigger you jump when loading the saveloc.

**Comment by braem** [comment]
we probably need to force a trigger collision calculation on teleporting

**Comment by xen-000** [comment]
This seems to have been fixed when practice mode was made to use the save-state system.

**Comment by hexaflexahexagon** [comment]
still happens for me, but only when the timer is running. easy to repro on triggertests since it has a start entity and a no-jump trigger in the main room
